routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@getHome')
    ->name('home');
Route::get('book-print', 'HomeController@bookPrintIndex')
    ->name('book-print.index');

Route::resource('writer', 'WriterController')->only([
    'show',
    'update',
]);
Route::resource('book', 'BookController')->only([
    'show',
    'update',
]);
Route::resource('publisher', 'PublisherController')->only([
    'show',
    'update',
]);

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'title',
        'publisher_id',
        'book_type_id',
    ];

    public function publisher()
    {
        return $this->belongsTo(Publisher::class, 'publisher_id');
    }

    public function bookType()
    {
        return $this->belongsTo(BookType::class, 'book_type_id');
    }

    public function authors()
    {
        return $this->belongsToMany(Writer::class, 'book_writers', 'book_id', 'writer_id')
            ->wherePivot('writer_status', Writer::sAuthor);
    }

    public function translators()
    {
        return $this->belongsToMany(Writer::class, 'book_writers', 'book_id', 'writer_id')
            ->wherePivot('writer_status', Writer::sTranslator);
    }

    public function writers()
    {
        return $this->belongsToMany(Writer::class, 'book_writers', 'book_id', 'writer_id');
    }

    public function bookPrints()
    {
        return $this->hasMany(BookPrint::class, 'book_id')
            ->orderBy('print_run', 'desc');
    }

    public function subscribedUsers()
    {
        return $this->belongsToMany(
            User::class,
            'user_subscriptions',
            'book_id',
            'user_id'
        );
    }
}

app/Models/BookType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BookType extends Model
{
    protected $fillable = [
        'name',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Book;
use App\Services\BookService;

use App\Support\MetaData;

class BookController extends Controller
{
    /**
     * @var BookService
     */
    protected $bookService;

    public function __construct(BookService $bookService)
    {
        $this->bookService = $bookService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        $book->load([
            'authors',
            'translators',
            'publisher',
            'bookPrints',
        ]);

        $user = auth()->user();

        $subscribed = false;

        if ($user) {
            $subscribed = $user->subscribedBooks()->wherePivot('book_id', $book->id)->first() ? true : false;
        }

        $meta = new MetaData([
            'title' => $book->title,
        ]);

        return view('book.show', [
            'book' => $book,
            'subscribed' => $subscribed,
            'meta' => $meta,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        if (!auth()->check()) {
            return redirect()->route('register');
        }

        $formData = $request->validate([
            'subscribe' => 'in:0,1',
        ]);

        if (array_key_exists('subscribe', $formData)) {
            $this->bookService->setSubscribeBook(
                auth()->user(),
                $book,
                (boolean)$formData['subscribe']
            );
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        //
    }
}

resources/views/book/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id="author">
  <div class="row mb-3">
    <div class="col-12 col-md-6 text-center text-md-left">
      <h3>{{ $book->title }}</h3>
    </div>

    <div class="col-12 col-md-6 text-center text-md-right">
      <form
        method="post"
        action="{{ route('book.update', $book->id) }}"
        @if(!$subscribed)
          data-confirm="{{ __('Bu kitaba ait her yeni baskıda e-posta alacaksınız. Emin misiniz?') }}"
        @endif
      >
        @csrf
        <input type="hidden" name="writer_id" value="{{ $book->id }}">
        <input type="hidden" name="_method" value="put">
        @if(!$subscribed)
          <input type="hidden" name="subscribe" value="1">
          <button type="submit" class="btn btn-outline-success">Bildirimleri Aç</button>
        @else
          <input type="hidden" name="subscribe" value="0">
          <button type="submit" class="btn btn-success">Bildirimleri Kapat</button>
        @endif
      </form>
    </div>
  </div>

  <p>
    <strong>{{ __('Yayıncı:') }}</strong>
    <a href="{{ route('publisher.show', $book->publisher_id) }}">
      {{ $book->publisher->title }}
    </a>
  </p>
  <p>
    <strong>{{ __('Yazar:') }}</strong>
    @foreach($book->authors as $writer)
      <a href="{{ route('writer.show', $writer->id) }}"
      >{{ $writer->name }}</a>@if(!$loop->last),@endif
    @endforeach
  </p>
  @if($book->translators->count())
    <p>
      <strong>{{ __('Çevirmen:') }}</strong>
      @foreach($book->translators as $writer)
        <a href="{{ route('writer.show', $writer->id) }}"
        >{{ $writer->name }}</a>@if(!$loop->last),@endif
      @endforeach
    </p>
  @endif

  @if($book->bookPrints()->count())
    <h5 class="mt-5 mb-3">{{ __('Baskılar') }}</h5>

    <table class="table table-sm table-responsive">
      <thead>
        <tr>
          <td>{{ __('Bandrol tarihi') }}</td>
          <td>{{ __('Baskı sayısı') }}</td>
        </tr>
      </thead>
      <tbody>
        @foreach($book->bookPrints as $bookPrint)
          <tr>
            <td class="p-2">{{ ba_format_date_fe($bookPrint->printed_on) }}</td>
            <td class="p-2 text-right">{{ $bookPrint->print_run }}</td>
          </tr>
        @endforeach
      </tbody>
    </table>
  @endif
</div>
@endsection