routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@getHome')
    ->name('home');
Route::get('book-print', 'HomeController@bookPrintIndex')
    ->name('book-print.index');

Route::resource('writer', 'WriterController')->only([
    'show',
    'update',
]);
Route::resource('book', 'BookController')->only([
    'show',
    'update',
]);
Route::resource('publisher', 'PublisherController')->only([
    'show',
    'update',
]);

app/Models/Writer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Writer extends Model
{
    const sAuthor = 1;
    const sTranslator = 2;

    protected $fillable = [
        'name',
        'is_author',
        'is_translator',
        'user_id',
    ];

    public $casts = [
        'is_author' => 'boolean',
        'is_translator' => 'boolean',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function booksAuthored()
    {
        return $this->belongsToMany(Book::class, 'book_writers', 'writer_id', 'book_id')
            ->wherePivot('writer_status', Writer::sAuthor);
    }

    public function booksTranslated()
    {
        return $this->belongsToMany(Book::class, 'book_writers', 'writer_id', 'book_id')
            ->wherePivot('writer_status', Writer::sTranslator);
    }

    public function books()
    {
        return $this->belongsToMany(Writer::class, 'book_writers', 'writer_id', 'book_id');
    }

    public function subscribedUsers()
    {
        return $this->belongsToMany(
            User::class,
            'user_subscriptions',
            'writer_id',
            'user_id'
        );
    }
}

app/Http/Controllers/WriterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Writer;
use App\Services\BookService;

use App\Support\MetaData;

class WriterController extends Controller
{
    /**
     * @var BookService
     */
    protected $bookService;

    public function __construct(BookService $bookService)
    {
        $this->bookService = $bookService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Writer  $writer
     * @return \Illuminate\Http\Response
     */
    public function show(Writer $writer)
    {
        $writer->load([
            'booksAuthored',
            'booksTranslated',
        ]);

        $user = auth()->user();

        $subscribed = false;

        if ($user) {
            $subscribed = $user->subscribedWriters()->wherePivot('writer_id', $writer->id)->first() ? true : false;
        }

        $meta = new MetaData([
            'title' => $writer->name,
        ]);

        return view('writer.show', [
            'writer' => $writer,
            'subscribed' => $subscribed,
            'meta' => $meta,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Writer  $writer
     * @return \Illuminate\Http\Response
     */
    public function edit(Writer $writer)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Writer  $writer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Writer $writer)
    {
        if (!auth()->check()) {
            return redirect()->route('register');
        }

        $formData = $request->validate([
            'subscribe' => 'in:0,1',
        ]);

        if (array_key_exists('subscribe', $formData)) {
            $this->bookService->setSubscribeWriter(
                auth()->user(),
                $writer,
                (boolean)$formData['subscribe']
            );
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Writer  $writer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Writer $writer)
    {
        //
    }
}

resources/views/writer/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id="author">
  <div class="row mb-3">
    <div class="col-12 col-md-6 text-center text-md-left">
      <h3>{{ $writer->name }}</h3>
      <p>
        @if($writer->is_author)
          Yazar
        @endif
        @if($writer->is_translator)
          Çevirmen
        @endif
      </p>
    </div>

    <div class="col-12 col-md-6 text-center text-md-right">
      <form
        method="post"
        action="{{ route('writer.update', $writer->id) }}"
        @if(!$subscribed)
          data-confirm="{{ __('Bu yazara/çevirmene ait her kitap çıktığınızda e-posta alacaksınız. Emin misiniz?') }}"
        @endif
      >
        @csrf
        <input type="hidden" name="writer_id" value="{{ $writer->id }}">
        <input type="hidden" name="_method" value="put">
        @if(!$subscribed)
          <input type="hidden" name="subscribe" value="1">
          <button type="submit" class="btn btn-outline-success">Bildirimleri Aç</button>
        @else
          <input type="hidden" name="subscribe" value="0">
          <button type="submit" class="btn btn-success">Bildirimleri Kapat</button>
        @endif
      </form>
    </div>
  </div>

  @if($writer->booksAuthored->count())
    <h4 class="mb-3">Yazdığı kitaplar</h4>
    <div class="row">
      @foreach($writer->booksAuthored as $book)
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <a class="book-item" href="{{ route('book.show', $book->id) }}">
            <h5>{{ $book->title }}</h5>
            <p>
              {{ $book->publisher->title }}
            </p>
          </a>
        </div>
      @endforeach
    </div>
  @endif

  @if($writer->booksTranslated->count())
    <h4 class="mb-3">Çevirdiği kitaplar</h4>
    <div class="row">
      @foreach($writer->booksTranslated as $book)
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <a class="book-item" href="{{ route('book.show', $book->id) }}">
            <h5>{{ $book->title }}</h5>
            <p>
              {{ $book->publisher->title }}
            </p>
          </a>
        </div>
      @endforeach
    </div>
  @endif
</div>
@endsection