routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@getHome')
    ->name('home');
Route::get('book-print', 'HomeController@bookPrintIndex')
    ->name('book-print.index');

Route::resource('writer', 'WriterController')->only([
    'show',
    'update',
]);
Route::resource('book', 'BookController')->only([
    'show',
    'update',
]);
Route::resource('publisher', 'PublisherController')->only([
    'show',
    'update',
]);

app/Models/Publisher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Publisher extends Model
{
    protected $fillable = [
        'name',
        'title',
    ];

    public function books()
    {
        return $this->hasMany(Book::class, 'publisher_id')
            ->orderBy('title');
    }

    public function subscribedUsers()
    {
        return $this->belongsToMany(
            User::class,
            'user_subscriptions',
            'publisher_id',
            'user_id'
        );
    }
}

app/Http/Controllers/PublisherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Publisher;
use App\Services\BookService;

use App\Support\MetaData;

class PublisherController extends Controller
{
    /**
     * @var BookService
     */
    protected $bookService;

    public function __construct(BookService $bookService)
    {
        $this->bookService = $bookService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Publisher  $publisher
     * @return \Illuminate\Http\Response
     */
    public function show(Publisher $publisher)
    {
        $publisher->load([
            'books',
        ]);

        $bookPrintList = $this->bookService->getPublisherBookPrintList($publisher);

        $user = auth()->user();

        $subscribed = false;

        if ($user) {
            $subscribed = $user->subscribedPublishers()->wherePivot('publisher_id', $publisher->id)->first() ? true : false;
        }

        $meta = new MetaData([
            'title' => $publisher->title,
        ]);

        return view('publisher.show', [
            'publisher' => $publisher,
            'bookPrintList' => $bookPrintList,
            'subscribed' => $subscribed,
            'meta' => $meta,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Publisher  $publisher
     * @return \Illuminate\Http\Response
     */
    public function edit(Publisher $publisher)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Publisher  $publisher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Publisher $publisher)
    {
        if (!auth()->check()) {
            return redirect()->route('register');
        }

        $formData = $request->validate([
            'subscribe' => 'in:0,1',
        ]);

        if (array_key_exists('subscribe', $formData)) {
            $this->bookService->setSubscribePublisher(
                auth()->user(),
                $publisher,
                (boolean)$formData['subscribe']
            );
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Publisher  $publisher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Publisher $publisher)
    {
        //
    }
}

resources/views/publisher/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id="author">
  <div class="row mb-3">
    <div class="col-12 col-md-6 text-center text-md-left">
      <h3>{{ $publisher->title }}</h3>
    </div>

    <div class="col-12 col-md-6 text-center text-md-right">
      <form
        method="post"
        action="{{ route('publisher.update', $publisher->id) }}"
        @if(!$subscribed)
          data-confirm="{{ __('Bu yayınevine ait her yeni baskıda e-posta alacaksınız. Emin misiniz?') }}"
        @endif
      >
        @csrf
        <input type="hidden" name="writer_id" value="{{ $publisher->id }}">
        <input type="hidden" name="_method" value="put">
        @if(!$subscribed)
          <input type="hidden" name="subscribe" value="1">
          <button type="submit" class="btn btn-outline-success">Bildirimleri Aç</button>
        @else
          <input type="hidden" name="subscribe" value="0">
          <button type="submit" class="btn btn-success">Bildirimleri Kapat</button>
        @endif
      </form>
    </div>
  </div>

  @if($publisher->books->count())
    <h4 class="mb-3">{{ __('Yayınlanan Kitaplar') }}</h4>
    <div class="row">
      @foreach($publisher->books as $book)
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <a class="book-item" href="{{ route('book.show', $book->id) }}">
            <h5>{{ $book->title }}</h5>
            <p>
              {{ $book->publisher->title }}
            </p>
          </a>
        </div>
      @endforeach
    </div>
  @endif

  @if($bookPrintList->count())
    <h5 class="mt-5 mb-3">{{ __('Baskılar') }}</h5>

    <table class="table table-sm table-responsive">
      <thead>
        <tr>
          <td>{{ __('Kitap adı') }}</td>
          <td>{{ __('Bandrol tarihi') }}</td>
          <td>{{ __('Baskı sayısı') }}</td>
        </tr>
      </thead>
      <tbody>
        @foreach($bookPrintList as $bookPrint)
          <tr>
            <td class="p-2">
              <a href="{{ route('book.show', $bookPrint->book_id) }}">
                {{ $bookPrint->book_title }}
              </a>
            </td>
            <td class="p-2">{{ ba_format_date_fe($bookPrint->printed_on) }}</td>
            <td class="p-2 text-right">{{ $bookPrint->print_run }}</td>
          </tr>
        @endforeach
      </tbody>
    </table>
  @endif
</div>
@endsection